[[redirects]]
  from = "/getlink"
  to = "https://api.short.io/links"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"